# -*- coding: utf-8 -*-
"""ProjetoCovidPy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXfpbPMkrhAWsJgxuqnj3MilHWgofT9T
"""

import pandas as pd
import plotly.express as px
import streamlit as st 

#streamlit run codigoBase.py


#LENDO O DATASET
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

#MELHORANDO O NOME DAS COLUNAS DA TABELA
df = df.rename(columns={'newDeaths': 'Novos óbitos','newCases': 'Novos casos','deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes','totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes'})

#SELECÃO DO ESTADO
estados = list(df['state'].unique()) #lista de estados
State = st.sidebar.selectbox('Qual Estado?', estados)

#SELEÇÃO DA COLUNA
#column ='Casos por 100 mil habitantes'
colunas = ['Novos óbitos','Novos casos','Óbitos por 100 mil habitantes','Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)

#SELEÇÃO DAS LINHAS QUE PERTECEM AO ESTADO 
df = df[df['state'] == State]

fig = px.line(df, x="date", y=column, title=column + ' - ' + State)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

#CONFIGURA TIPOS DE TEXTO NO 
st.title('ANALISE EXPLORATORIA DE DADOS')
st.markdown('CASOS SOBRE COVID - BRASIL')

st.write('Nessa aplicação, o usuário tem a opção de escolher o estado e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')

st.plotly_chart(fig, use_container_width=True)

#fig.show()

st.caption('Os dados foram obtidos a partir do site: https://github.com/wcota/covid19br')